server:
  port: 5000

spring:
  application:
    name: BUYER-APP
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

feign:
  client:
    config:
      default:
        connectionTimeout: 10000
        readTimeout: 10000
        loggerLevel: basic
  circuitbreaker:
    enabled: true

eureka:
  client:
    healthcheck:
      enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${DEFAULT_ZONE:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true

AWS_METADATA_URL: http://169.254.170.2/v2/metadata